CREATE TABLE COMMONS_COMMONS
(
    ID CHAR(36) NOT NULL PRIMARY KEY,
    SITE_ID VARCHAR2(99) NOT NULL,
    EMBEDDER VARCHAR2(24) NOT NULL
);

CREATE TABLE COMMONS_POST
(
    ID char(36) NOT NULL PRIMARY KEY,
    CONTENT CLOB NOT NULL,
    CREATOR_ID VARCHAR2(99) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    MODIFIED_DATE DATE NOT NULL,
    RELEASE_DATE DATE NOT NULL
);
CREATE INDEX COMMONS_POST_CREATOR_ID_IDX on COMMONS_POST (CREATOR_ID);

CREATE TABLE COMMONS_COMMONS_POST
(
    COMMONS_ID CHAR(36),
    POST_ID CHAR(36),
    CONSTRAINT COMMONS_ID_POST_ID_U UNIQUE (COMMONS_ID,POST_ID),
    CONSTRAINT COMMONS_COMMONS_POST_C_ID_FK FOREIGN KEY (COMMONS_ID) REFERENCES COMMONS_COMMONS(ID),
    CONSTRAINT COMMONS_COMMONS_POST_P_ID_FK FOREIGN KEY (POST_ID) REFERENCES COMMONS_POST(ID)
);

CREATE TABLE COMMONS_COMMENT
(
    ID CHAR(36) NOT NULL PRIMARY KEY,
    POST_ID CHAR(36),
    CONTENT CLOB NOT NULL,
    CREATOR_ID VARCHAR2(99) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    MODIFIED_DATE DATE NOT NULL,
    CONSTRAINT COMMONS_COMMENT_POST_ID_FK FOREIGN KEY (POST_ID) REFERENCES COMMONS_POST(ID)
);
CREATE INDEX COMMONS_COMMENT_CREATOR_ID_IDX on COMMONS_COMMENT (CREATOR_ID);
CREATE INDEX COMMONS_COMMENT_POST_ID_IDX on COMMONS_COMMENT (POST_ID);