CREATE TABLE PROFILE_TYPED_VALUES_T
   (    ID NUMBER(19,0) NOT NULL,
        USER_UUID VARCHAR2(36) NOT NULL,
        VALUE_GROUP VARCHAR2(150) NOT NULL,
        TYPE VARCHAR2(256) NOT NULL,
        TYPE_QUALIFIER VARCHAR2(256),
        VALUE VARCHAR2(256) NOT NULL,
        PRIMARY KEY (ID)
   );

create sequence PROFILE_TYPED_VALUES_S;
